# Generated by Django 4.2.1 on 2023-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='ver_num',
            field=models.IntegerField(default=0, verbose_name='Версия'),
        ),
    ]
